### ISSUE TITLE
Processing data for data transportation

### ISSUE THREAD

**Issue by lin9703** [euphony-io/looking-for-job#11]
Process for sending and receiving data

### Send data
1. Create a data class and store the data there.
2. Convert to string in json format.

### Receive data
1. Convert string to data class.

**Comment by dlwlstks96** [comment]
It would be better to send and receive data using GSON!
https://web-inf.tistory.com/64
@6loss0m

**Comment by dlwlstks96** [comment]
```
private Map<String, String> data = new HashMap<>();
data.put("name", editTextName.getText().toString());
data.put("birth", editTextBirth.getText().toString());
data.put("number", editTextNumber.getText().toString());
data.put("address", editTextAddress.getText().toString());
data.put("career", editTextCareer.getText().toString());

Gson gson = new Gson();
String output = gson.toJson(data);
```
How about the above code instead of creating a separate class to hold the data?
We can send data in the form of a map!
the data is sent as shown below.
@6loss0m @lin9703 @dd-create 

![looking_for_job_ex2](https://user-images.githubusercontent.com/72801465/130072837-b880b2e5-8e71-4000-a2e7-86997bd66fe8.JPG)

**Comment by lin9703** [comment]
> ```
> private Map<String, String> data = new HashMap<>();
> data.put("name", editTextName.getText().toString());
> data.put("birth", editTextBirth.getText().toString());
> data.put("number", editTextNumber.getText().toString());
> data.put("address", editTextAddress.getText().toString());
> data.put("career", editTextCareer.getText().toString());
> 
> Gson gson = new Gson();
> String output = gson.toJson(data);
> ```
> 
> How about the above code instead of creating a separate class to hold the data?
> We can send data in the form of a map!
> the data is sent as shown below.
> @6loss0m @lin9703 @dd-create
> 
> ![looking_for_job_ex2](https://user-images.githubusercontent.com/72801465/130072837-b880b2e5-8e71-4000-a2e7-86997bd66fe8.JPG)

I think it's good.
