### ISSUE TITLE
Role 

### ISSUE THREAD

**Issue by lin9703** [euphony-io/looking-for-job#2]
We divided the roles based on functions.

**Comment by lin9703** [comment]
- Function to receive resume information - Page 2-1 (assigned @dlwlstks96 )
- Show resume received from listener - Page 2-2 (assigned @6loss0m )
- Euphony Listener (using permission) - Page 2-2 (assigned @lin9703 )
- Euphony speaker + business card send/receive function - Page 1 + Page 2-1 (assigned @dd-create )

**Comment by dlwlstks96** [comment]
We finish the issue because we have finished the sample project for each role.
