### ISSUE TITLE
UI and Contents

### ISSUE THREAD

**Issue by dlwlstks96** [euphony-io/looking-for-job#3]
@lin9703 @dd-create @6loss0m 

This is our UI.

![LFJ_UI](https://user-images.githubusercontent.com/72801465/129723055-963ef099-0d1c-42a7-b9fc-b9e9c6ffba10.png)

**Comment by lin9703** [comment]
First, develop functionality and add design.

**Comment by dlwlstks96** [comment]
We closed the issue because we made a sample app based on the UI.
